MarketDataHandling:
  exchange: binance
  source: binance.spot.depth
  destination: binance.spot.depth.stream
  task: binance.spot.depth
  estimators:
    - name: mid
      settings:
        decimals: 2
        index: 0
    - name: vwap
      settings:
        decimals: 2
        bidIndex: 5
        askIndex: 0
        arrayLength: 5

DataPreprocessing:
  exchange: binance
  source: binance.spot.depth.stream
  destination: indicators
  aggregationPeriod: 1
  aggregationMetric:
  indicators:
    - name: log-returns
      settings:
        start: 0
        end: -1
    - name: mean
      settings:
    - name: ewma
      settings:
        lambda: 0.94
    - name: garch
      settings:
        alpha: 0.15
        beta: 0.8
    
TradingLogic:
  exchange: binance
  source: [spot.trades, futures.trades, indicators]
  destination: feedback
  strategy: 