MarketDataHandling:
  exchange: binance
  source: binance.spot.depth
  destination: stream:binance.spot.depth
  task: binance.spot.depth.estimators
  estimators:
    - name: mid
      settings:
        decimals: 2
        index: 0
    - name: vwap
      settings:
        decimals: 2
        bidIndex: 5
        askIndex: 0
        arrayLength: 5

MarketDataStatistics:
  sources: [stream:binance.spot.depth.BTCUSDT]
  destinations: indicators
  initialNumberOfEntries: 100
  aggregationPeriod: 15000
  estimators:
    - name: returns
      settings:
        decimals: 2
    - name: mean
      settings:
        decimals: 2
    # - name: ewma
    #   settings:
    #     lambda: 0.94
    # - name: garch
    #   settings:
    #     alpha: 0.15
    #     beta: 0.8
    
TradingLogic:
  exchange: binance
  source: [spot.trades, futures.trades, indicators]
  destination: feedback
  strategy: 