MarketDataHandling:
  exchange: binance
  source: binance.spot.depth
  destination: binance.spot.depth
  task: binance.spot.depth.prices
  prices:
    - name: mid
      settings:
        decimals: 2
        index: 0
    - name: vwap
      settings:
        decimals: 2
        bidIndex: 19
        askIndex: 0
        arrayLength: 19

MarketDataStatistics:
  sources: binance.spot.depth.BTCUSDT
  destination: binance.spot.depth.BTCUSDT.1m
  initialNumberOfEntries: 100
  aggregationPeriod: 1m
  signals:
    - name: returns
      settings:
        decimals: 2
    - name: sma
      settings:
        decimals: 2
    - name: ewma
      settings:
        lambda: 0.94
        decimals: 2
    
TradingLogic:
  exchange: binance
  source: [spot.trades, futures.trades, indicators]
  destination: feedback
  strategy: 