MarketDataHandling:
  exchange: binance
  source: binance.spot.depth
  task: binance.spot.depth
  prices:
    - name: mid
      settings:
        decimals: 2
        index: 0
    - name: vwap
      settings:
        decimals: 2
        bidIndex: 5
        askIndex: 0
        arrayLength: 5

MarketDataStatistics:
  sources: binance.spot.depth.BTCUSDT
  initialNumberOfEntries: 100
  aggregationPeriod: 1m
  signals:
    - name: returns
      settings:
        decimals: 2
    - name: sma
      settings:
        decimals: 2
    - name: ewma-slow
      settings:
        lambda: 0.035
        decimals: 2
    - name: ewma-fast
      settings:
        lambda: 0.90
        decimals: 2
    
TradingLogic:
  sources: [spot.trades, futures.trades, binance.spot.depth.BTCUSDT.1m]
  settings:
    exchange: binance
    strategy: dev