[package]
name = "exchange_subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
zmq = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
binance = []
